Added text and images
DANS-KNAW/dataverse-bridge-service pull request #8
Opened 2019-02-04 09:45 UTC by ekoi

DDN-454

2019-02-05 07:59 UTC, PaulBoon commented on README.md
> +
The 'Archive Popup' is still showing the password and username as input, those are different now. We should update this screen dump.

2019-02-05 09:00 UTC, PaulBoon commented on README.md
> +
instead of the curl PUT -d, use curl PUT  --upload-file, otherwise the name of the file is in the setting instead of the file content!

2019-02-05 09:08 UTC, PaulBoon commented on README.md
> +Update datasetversion set darnote ='' where id in (select dv.id from datasetversion dv, dataset d where dv.dataset_id=d.id and dv.darnote='FAILED' and dv.versionnumber=1 and dv.minorversionnumber=4 a
change datnote ='' to darnote=null

2019-02-05 09:10 UTC, PaulBoon requested changes
Please look at the suggested changes

2019-02-05 10:46 UTC, ekoi commented on README.md
> +
Done

2019-02-07 12:18 UTC, PaulBoon approved these changes

2019-04-11 11:24 UTC, merged